---
name: Coverage

on:
  push:
    branches-ignore:
      - develop
      - main

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --verbose -- --nocapture
        env:
          RUST_BACKTRACE: full
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: -Cinstrument-coverage -Ccodegen-units=1 -Clink-dead-code -Coverflow-checks=off
          RUSTDOCFLAGS: -Cinstrument-coverage -Ccodegen-units=1 -Clink-dead-code -Coverflow-checks=off

      - name: rust-grcov
        uses: actions-rs/grcov@v0.1

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
